spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:  jdbc:postgresql://localhost:5432/note-app
    username: postgres
    password: 2188

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true

  logging:
    level:
      root: INFO
    appenders:
      - type: console
